### ISSUE TITLE
Revamp safe-react-components

### ISSUE THREAD

**Issue by yagopv** [safe-global/safe-react-components#198]
#  What it solves
With this revamp we want to create a v2 of the library exporting the Safe theme and the real necessary and useful components.

With this new Safe theme any consumer web application can use the [@mui](https://mui.com) library with the exported theme and get the look and feel of the Safe

# Tasks

- [x] Export the Safe theme for use in all the client applications
- [ ] Add the real necessary components migrated to mui 5:
    - [ ] AddressInput
    - [x] EthHashInfo
    - [x] ExplorerButton
- [x] Remove all the unnecessary components and libraries
- [x] Create Stories for demoing the basic components with the new theme

[revamp branch](https://github.com/safe-global/safe-react-components/tree/revamp-safe-react-components)

**Comment by JagoFigueroa** [comment]
Looks good to me, approving all of the linked PRs 👍
